//Register API
###
POST http://127.0.0.1:8000/api/users/signup
Accept: application/json
Content-Type: application/json

{
  "username": "ritik",
  "password": "ritik123"
}

//Login API
###
POST http://127.0.0.1:8000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "username": "ritik",
  "password": "ritik123"
}


//Create Task API
###
POST http://127.0.0.1:8000/api/tasks
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczNjQ0MjY0OSwiZXhwIjoxNzM2NDQ2MjQ5fQ.cy0U_ght01c6zfrxgYS-QIi1dxNQlXZBA9yDLVzQjFw
Content-Type: application/json

{
  "title": "Complete Project",
  "description": "Finish the backend and frontend",
  "priority": "High",
  "due_date": "2024-01-10",
  "category_id": 1,
  "comment":"This is very critical task",
  "status":"TO DO"
}


//Get Task API
###
GET http://127.0.0.1:8000/api/tasks
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczNjQ0MjY0OSwiZXhwIjoxNzM2NDQ2MjQ5fQ.cy0U_ght01c6zfrxgYS-QIi1dxNQlXZBA9yDLVzQjFw



//Update Task API
###
PUT http://127.0.0.1:8000/api/tasks/9
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczNjQ0MjY0OSwiZXhwIjoxNzM2NDQ2MjQ5fQ.cy0U_ght01c6zfrxgYS-QIi1dxNQlXZBA9yDLVzQjFw

{
  "title": "Updated Task Title",
  "description": "Updated description",
  "priority": "High",
  "due_date": "2024-02-01",
  "category_id": 3,
  "status":"In Progress",
  "comment":"Working on this task",

}


//Delete Task API
###
DELETE http://127.0.0.1:8000/api/tasks/:id
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzYzNjExNDQsImV4cCI6MTczNjM2NDc0NH0.hekEMIOncQ9LT9yO4H38RRlv5LVfY0m5l89q47hw8n4
